"""Synthetic mobile-financial-services scenario library for upay Shield.

This module builds a fully synthetic, reproducible world of customers
(wallets), merchants and agents, plus the transactions, device records and
login events they produce. It exists so that the risk pipeline can be
developed and evaluated on data with a *known* but non-trivial structure.

Design commitments (see ``AGENTS.md`` and ``docs/architecture.md``):

* **Synthetic only.** No real names, phone numbers, account numbers or any
  other personal data are produced. Identifiers are opaque counters.
* **Deterministic.** All randomness flows from one seeded
  :class:`numpy.random.Generator`. The same :class:`SimConfig` produces the
  same world, byte for byte.
* **Money is integer poisha.** 1 BDT = 100 poisha. No monetary value in this
  module is ever a float.
* **Timestamps are UTC.** Every emitted timestamp is an integer epoch second
  that is converted to a timezone-aware UTC timestamp at the end. Behavioural
  hour-of-day is generated in Asia/Dhaka (a fixed UTC+06:00 offset; Bangladesh
  has no daylight saving) and stored as UTC.
* **Overlapping distributions.** Fraud is generated by rich, multi-event
  stochastic processes, not by a threshold. Normal activity deliberately
  contains high-value, bursty and new-device behaviour (the benign
  confounders) so that no simple rule separates the classes.
* **Labels are quarantined.** Ground truth is written only to the
  ``scenario_truth`` frame, keyed by transaction id. It is never a column of
  the transactions frame.

The public entry point is :func:`build_world`.
"""

from __future__ import annotations

import datetime as _dt
import math
from collections.abc import Sequence
from dataclasses import dataclass, field

import numpy as np
import pandas as pd

# ---------------------------------------------------------------------------
# Generator identity and the synthetic clock
# ---------------------------------------------------------------------------

#: Bumped whenever the generated structure changes in a way that would alter
#: an existing seed's output. Recorded in every manifest.
GENERATOR_VERSION = "1.0.0"

#: The synthetic clock starts at 2026-01-01T00:00:00 in Asia/Dhaka, which is
#: 2025-12-31T18:00:00Z. Anchoring day boundaries to local midnight keeps the
#: behavioural hour-of-day features exact and free of modular arithmetic.
SIM_START_UTC_EPOCH: int = int(
    _dt.datetime(2025, 12, 31, 18, 0, 0, tzinfo=_dt.timezone.utc).timestamp()
)

#: Local calendar date of synthetic day 0.
SIM_START_LOCAL_DATE: _dt.date = _dt.date(2026, 1, 1)

#: Asia/Dhaka is a fixed +06:00 offset with no daylight saving.
LOCAL_UTC_OFFSET_SECONDS: int = 6 * 3600

SECONDS_PER_DAY: int = 86_400

# ---------------------------------------------------------------------------
# Geography — synthetic regions and areas
# ---------------------------------------------------------------------------

#: Synthetic regions. Names are real Bangladeshi divisions because that makes
#: peer groups legible to an analyst; the coordinates are only used for
#: plausible inter-location distances and are not tied to any real customer.
REGIONS: tuple[str, ...] = (
    "dhaka",
    "chattogram",
    "khulna",
    "rajshahi",
    "sylhet",
    "barishal",
    "rangpur",
    "mymensingh",
)

REGION_CENTROIDS: dict[str, tuple[float, float]] = {
    "dhaka": (23.8103, 90.4125),
    "chattogram": (22.3569, 91.7832),
    "khulna": (22.8456, 89.5403),
    "rajshahi": (24.3745, 88.6042),
    "sylhet": (24.8949, 91.8687),
    "barishal": (22.7010, 90.3535),
    "rangpur": (25.7439, 89.2752),
    "mymensingh": (24.7471, 90.4203),
}

REGION_WEIGHTS: tuple[float, ...] = (0.34, 0.20, 0.10, 0.09, 0.09, 0.06, 0.07, 0.05)

AREAS: dict[str, tuple[str, ...]] = {
    "dhaka": ("mirpur", "gulshan", "dhanmondi", "uttara"),
    "chattogram": ("agrabad", "halishahar", "pahartali"),
    "khulna": ("sonadanga", "khalishpur", "daulatpur"),
    "rajshahi": ("boalia", "motihar", "shaheb-bazar"),
    "sylhet": ("zindabazar", "ambar khana", "south surma"),
    "barishal": ("band road", "natun bazar", "rupatali"),
    "rangpur": ("jahaj company", "mahiganj", "darshana"),
    "mymensingh": ("ganginarpar", "charpara", "kewatkhali"),
}

#: Transaction channel vocabulary. Must remain a subset of
#: ``backend.app.intelligence.features.schema.CHANNELS``.
CHANNEL_APP = "app"
CHANNEL_USSD = "ussd"
CHANNEL_AGENT = "agent_terminal"
CHANNEL_WEB = "web"
CHANNEL_API = "api"

#: Transaction type vocabulary. Must remain a subset of
#: ``backend.app.intelligence.features.schema.TRANSACTION_TYPES``.
TYPE_SEND = "send_money"
TYPE_CASH_IN = "cash_in"
TYPE_CASH_OUT = "cash_out"
TYPE_MERCHANT = "merchant_payment"
TYPE_BILL = "bill_payment"
TYPE_RECHARGE = "mobile_recharge"
TYPE_SETTLEMENT = "agent_settlement"

MERCHANT_KINDS: tuple[str, ...] = (
    "retail",
    "grocery",
    "restaurant",
    "pharmacy",
    "biller",
    "telco",
    "ecommerce",
)

#: Relative probability of each merchant kind.
MERCHANT_KIND_WEIGHTS: tuple[float, ...] = (0.24, 0.14, 0.16, 0.10, 0.12, 0.06, 0.18)

#: Merchant kind that legitimately receives bill payments.
BILLER_KIND = "biller"

#: Merchant kind that legitimately receives mobile recharges.
TELCO_KIND = "telco"

# ---------------------------------------------------------------------------
# Behavioural hour profile (local time, index = hour 0..23)
# ---------------------------------------------------------------------------

#: A calm diurnal curve peaking in the evening, which is typical of retail
#: mobile-money usage. Values are relative weights and are normalised below.
GLOBAL_HOUR_PROFILE: np.ndarray = np.array(
    [
        1.1, 0.6, 0.4, 0.3, 0.3, 0.5,
        1.2, 2.1, 3.2, 3.8, 3.9, 4.0,
        4.2, 4.4, 4.3, 4.0, 4.1, 4.8,
        5.6, 6.0, 5.4, 3.8, 2.4, 1.5,
    ],
    dtype=float,
)
GLOBAL_HOUR_PROFILE = GLOBAL_HOUR_PROFILE / GLOBAL_HOUR_PROFILE.sum()

#: Fraction of customers whose behaviour is shifted towards the night. Real
#: populations are heterogeneous; a single global curve would make any
#: hour-of-day signal suspiciously clean.
NIGHT_OWL_SHARE = 0.18

# ---------------------------------------------------------------------------
# Amount model. All medians are in BDT; every returned value is integer poisha.
# ---------------------------------------------------------------------------

#: (median BDT, log-sigma, minimum BDT, maximum BDT) per transaction type.
AMOUNT_MODEL: dict[str, tuple[float, float, float, float]] = {
    TYPE_RECHARGE: (100.0, 0.75, 10.0, 2_000.0),
    TYPE_BILL: (1_200.0, 0.70, 150.0, 15_000.0),
    TYPE_MERCHANT: (700.0, 1.00, 50.0, 25_000.0),
    TYPE_SEND: (1_500.0, 1.10, 50.0, 50_000.0),
    TYPE_CASH_OUT: (3_000.0, 0.85, 200.0, 60_000.0),
    TYPE_CASH_IN: (4_000.0, 0.90, 200.0, 100_000.0),
    TYPE_SETTLEMENT: (50_000.0, 1.00, 5_000.0, 500_000.0),
}

#: Share of ordinary transactions that are legitimately large. This is one of
#: the mechanisms that keeps a naive amount threshold from working.
BENIGN_LARGE_SHARE = 0.05
BENIGN_LARGE_FACTOR = (1.9, 4.5)

# ---------------------------------------------------------------------------
# Fraud budget
# ---------------------------------------------------------------------------

#: Share of the requested transaction count reserved for fraud episodes. This
#: is a *budget*, not a guarantee: each family draws a stochastic number of
#: transactions per episode, so the realised fraud rate lands slightly below
#: this value and is always reported as-is in the manifest.
FRAUD_SHARE = 0.05

#: Fraud families: (name, share of fraud budget, mean transactions per episode).
FRAUD_FAMILIES: tuple[tuple[str, float, float], ...] = (
    ("ato", 0.14, 3.0),
    ("velocity_burst", 0.19, 5.0),
    ("mule_fanin", 0.13, 9.0),
    ("circular", 0.07, 4.0),
    ("agent_cashout_spike", 0.11, 8.0),
    ("scam_escalation", 0.16, 4.0),
    ("scam_split", 0.20, 8.0),
)

#: Probability that an episode is "subtle": magnitudes, recipients and hours
#: are pulled towards the ordinary distribution so that easy rules miss it.
SUBTLE_EPISODE_SHARE = 0.34

#: Probability that a transaction's status is not ``completed``. Held equal
#: across classes on purpose: status is a *forbidden* model input, and making
#: it correlate with the label would tempt a leak.
STATUS_FAILED_SHARE = 0.021
STATUS_PENDING_SHARE = 0.013

SEVERITIES: tuple[str, ...] = ("none", "low", "medium", "high")


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SimConfig:
    """Everything that determines a generated world.

    Attributes:
        seed: Master random seed. Same seed plus same fields equals same
            world, byte for byte.
        n_wallets: Number of customer wallets.
        n_merchants: Number of merchant entities.
        n_agents: Number of agent entities.
        n_transactions: Target total number of transactions. The realised
            total is exact unless the requested total is too small to hold
            the fraud budget, in which case it is reported honestly.
        days: Length of the synthetic window in local days.
    """

    seed: int = 42
    n_wallets: int = 1_000
    n_merchants: int = 50
    n_agents: int = 30
    n_transactions: int = 60_000
    days: int = 90

    def __post_init__(self) -> None:
        if self.n_wallets < 10:
            raise ValueError("n_wallets must be at least 10")
        if self.n_merchants < 3:
            raise ValueError("n_merchants must be at least 3")
        if self.n_agents < 2:
            raise ValueError("n_agents must be at least 2")
        if self.n_transactions < 100:
            raise ValueError("n_transactions must be at least 100")
        if self.days < 7:
            raise ValueError("days must be at least 7")

    @classmethod
    def small(cls, seed: int = 7) -> SimConfig:
        """Return a fast preset for tests and CI (low thousands of rows)."""
        return cls(
            seed=seed,
            n_wallets=60,
            n_merchants=8,
            n_agents=5,
            n_transactions=2_000,
            days=30,
        )


@dataclass(frozen=True)
class Location:
    """A synthetic place used for transactions and logins.

    Attributes:
        location_id: Stable identifier referenced by transactions/logins.
        region: Synthetic region the place belongs to.
        area: Human-readable area label inside the region.
        latitude: Synthetic latitude in decimal degrees.
        longitude: Synthetic longitude in decimal degrees.
    """

    location_id: str
    region: str
    area: str
    latitude: float
    longitude: float


@dataclass
class World:
    """The complete generated world.

    Attributes:
        config: The configuration that produced this world.
        run_id: Scenario run identifier stamped onto every row.
        entities: Customer, merchant and agent entities.
        devices: Devices, each owned by exactly one entity.
        transactions: Transactions, one row per event, time ordered.
        login_events: Authentication attempts.
        scenario_truth: Ground truth keyed by ``transaction_id``. The only
            place a fraud label exists. Never join this into a scoring frame.
        locations: Reference table mapping ``location_id`` to coordinates.
        stats: Counts and class mix, suitable for the manifest.
    """

    config: SimConfig
    run_id: str
    entities: pd.DataFrame
    devices: pd.DataFrame
    transactions: pd.DataFrame
    login_events: pd.DataFrame
    scenario_truth: pd.DataFrame
    locations: pd.DataFrame
    stats: dict[str, object] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Small numeric helpers
# ---------------------------------------------------------------------------


def _largest_remainder(weights: np.ndarray, total: int) -> np.ndarray:
    """Allocate ``total`` integer units in proportion to ``weights``.

    Uses the largest-remainder method so the allocation sums exactly to
    ``total`` and is stable under ties (``argsort`` with ``kind='stable'``).
    """
    w = np.asarray(weights, dtype=float)
    s = float(w.sum())
    if s <= 0.0:
        raise ValueError("weights must have a positive sum")
    raw = w / s * total
    base = np.floor(raw).astype(np.int64)
    shortfall = total - int(base.sum())
    if shortfall > 0:
        order = np.argsort(-(raw - base), kind="stable")
        base[order[:shortfall]] += 1
    return base


def _round_amount(poisha: float, rng: np.random.Generator) -> int:
    """Round a monetary value to a realistic denomination.

    Real transfers cluster on round numbers. The mixture below produces a
    spread of ৳1, ৳10 and ৳50 granularity, which also means amount values
    collide often enough to make exact-value rules useless.
    """
    draw = rng.random()
    if draw < 0.42:
        step = 5_000  # 50 BDT
    elif draw < 0.72:
        step = 1_000  # 10 BDT
    else:
        step = 100  # 1 BDT
    return max(step, int(round(poisha / step)) * step)


def _draw_amount(
    rng: np.random.Generator,
    txn_type: str,
    scale: float = 1.0,
    sigma: float | None = None,
) -> int:
    """Draw a plausible amount in integer poisha for a transaction type."""
    median_bdt, default_sigma, lo_bdt, hi_bdt = AMOUNT_MODEL[txn_type]
    sigma = default_sigma if sigma is None else sigma
    median_poisha = median_bdt * 100.0 * scale
    value = float(rng.lognormal(mean=math.log(max(median_poisha, 1.0)), sigma=sigma))
    lo = lo_bdt * 100.0
    hi = hi_bdt * 100.0
    value = min(max(value, lo), hi)
    return _round_amount(value, rng)


def _day_start_utc(day_index: int) -> int:
    """Return the UTC epoch second at which a local day begins."""
    return SIM_START_UTC_EPOCH + day_index * SECONDS_PER_DAY


def _local_date(day_index: int) -> _dt.date:
    """Return the local calendar date of a synthetic day index."""
    return SIM_START_LOCAL_DATE + _dt.timedelta(days=day_index)


def _haversine_km(lat1: float, lon1: float, lat2: float, lon2: float) -> float:
    """Great-circle distance in kilometres between two synthetic points."""
    radius = 6371.0088
    p1, p2 = math.radians(lat1), math.radians(lat2)
    dp = p2 - p1
    dl = math.radians(lon2 - lon1)
    a = math.sin(dp / 2) ** 2 + math.cos(p1) * math.cos(p2) * math.sin(dl / 2) ** 2
    return 2 * radius * math.asin(math.sqrt(a))


def build_locations() -> tuple[Location, ...]:
    """Build the synthetic location reference table.

    Coordinates are derived from the region centroid plus a deterministic
    offset so that the table is independent of the random seed.
    """
    locations: list[Location] = []
    for region in REGIONS:
        base_lat, base_lon = REGION_CENTROIDS[region]
        for i, area in enumerate(AREAS[region]):
            dlat = ((i * 7) % 11 - 5) * 0.0135
            dlon = ((i * 5) % 13 - 6) * 0.0121
            slug = area.replace(" ", "-")
            locations.append(
                Location(
                    location_id=f"{region}.{slug}",
                    region=region,
                    area=area,
                    latitude=round(base_lat + dlat, 6),
                    longitude=round(base_lon + dlon, 6),
                )
            )
    return tuple(locations)


# ---------------------------------------------------------------------------
# The builder
# ---------------------------------------------------------------------------


class WorldBuilder:
    """Generates one synthetic world from a :class:`SimConfig`.

    The class holds only plain Python and NumPy state during generation and
    converts to pandas at the end. That keeps every intermediate value
    deterministic and avoids depending on pandas' inference behaviour
    mid-build.
    """

    def __init__(self, config: SimConfig) -> None:
        self.cfg = config
        self.rng = np.random.default_rng(config.seed)
        self.run_id = f"run-{config.seed}"

        self.locations: tuple[Location, ...] = build_locations()
        self._loc_region: np.ndarray = np.array(
            [REGIONS.index(loc.region) for loc in self.locations], dtype=np.int64
        )

        # --- raw event buffers -------------------------------------------------
        self._txns: list[dict[str, object]] = []
        self._truth: list[dict[str, object]] = []
        self._logins: list[dict[str, object]] = []
        self._entity_rows: list[dict[str, object]] = []
        self._device_rows: list[dict[str, object]] = []
        self._uid = 0
        self._device_seq = 0
        self._identity_seq: dict[str, int] = {"customer": 0, "merchant": 0, "agent": 0}

        # --- per-entity caches -------------------------------------------------
        self._cust_ids: list[str] = []
        self._cust_region: np.ndarray = np.empty(0, dtype=np.int64)
        self._cust_created: np.ndarray = np.empty(0, dtype=np.int64)
        self._cust_start_day: np.ndarray = np.empty(0, dtype=np.int64)
        self._cust_end_day: np.ndarray = np.empty(0, dtype=np.int64)
        self._cust_median: np.ndarray = np.empty(0, dtype=np.float64)
        self._cust_device: list[str] = []
        self._cust_device2: list[str | None] = []
        self._cust_device2_day: np.ndarray = np.empty(0, dtype=np.int64)
        self._cust_hour_profile: list[np.ndarray] = []
        self._cust_contacts: list[list[int]] = []
        self._cust_merchants: list[list[int]] = []
        self._cust_agents: list[list[int]] = []
        self._cust_new_account: np.ndarray = np.empty(0, dtype=bool)
        self._cust_txn_count: np.ndarray = np.empty(0, dtype=np.int64)

        self._mer_ids: list[str] = []
        self._mer_region: np.ndarray = np.empty(0, dtype=np.int64)
        self._mer_kind: list[str] = []
        self._mer_location: np.ndarray = np.empty(0, dtype=np.int64)
        self._mer_weight: np.ndarray = np.empty(0, dtype=np.float64)
        self._mer_kind_index: dict[str, np.ndarray] = {}

        self._agt_ids: list[str] = []
        self._agt_region: np.ndarray = np.empty(0, dtype=np.int64)
        self._agt_location: np.ndarray = np.empty(0, dtype=np.int64)
        self._agt_device: list[str] = []
        self._agt_weight: np.ndarray = np.empty(0, dtype=np.float64)

        self._cust_id_index: dict[str, int] = {}
        self._fraud_eligible: np.ndarray = np.empty(0, dtype=np.int64)

    # -- emission primitives ------------------------------------------------

    def _next_identity(self, kind: str, width: int, prefix: str) -> str:
        self._identity_seq[kind] += 1
        return f"{prefix}{self._identity_seq[kind]:0{width}d}"

    def _mint_device(self, entity_id: str, first_seen: int, channel: str) -> str:
        """Create a device and record it in the device table."""
        self._device_seq += 1
        device_id = f"D{self._device_seq:06d}"
        self._device_rows.append(
            {
                "device_id": device_id,
                "entity_id": entity_id,
                "first_seen_at": int(first_seen),
                "channel": channel,
            }
        )
        return device_id

    def _draw_status(self) -> str:
        draw = self.rng.random()
        if draw < STATUS_FAILED_SHARE:
            return "failed"
        if draw < STATUS_FAILED_SHARE + STATUS_PENDING_SHARE:
            return "pending"
        return "completed"

    def _add_txn(
        self,
        *,
        sender_id: str,
        receiver_id: str,
        amount_poisha: int,
        txn_type: str,
        timestamp: int,
        device_id: str,
        location_id: str,
        status: str | None = None,
        is_fraud: bool = False,
        fraud_family: str | None = None,
        confounder_family: str | None = None,
        severity: str = "none",
    ) -> int:
        """Append one transaction plus its truth row; return the internal uid."""
        uid = self._uid
        self._uid += 1
        status = self._draw_status() if status is None else status
        self._txns.append(
            {
                "_uid": uid,
                "sender_id": sender_id,
                "receiver_id": receiver_id,
                "amount_poisha": int(amount_poisha),
                "type": txn_type,
                "timestamp": int(timestamp),
                "device_id": device_id,
                "location": location_id,
                "status": status,
            }
        )
        self._truth.append(
            {
                "_uid": uid,
                "is_fraud": bool(is_fraud),
                "fraud_family": fraud_family,
                "confounder_family": confounder_family,
                "scenario_severity": severity,
            }
        )
        sender_idx = self._cust_id_index.get(sender_id)
        if sender_idx is not None:
            self._cust_txn_count[sender_idx] += 1
        return uid

    def _add_login(
        self,
        *,
        entity_id: str,
        timestamp: int,
        device_id: str,
        success: bool,
        location_id: str,
    ) -> None:
        self._logins.append(
            {
                "entity_id": entity_id,
                "timestamp": int(timestamp),
                "device_id": device_id,
                "success": bool(success),
                "location": location_id,
            }
        )

    # -- sampling helpers ---------------------------------------------------

    def _draw_hour(self, profile: np.ndarray) -> int:
        return int(self.rng.choice(24, p=profile))

    def _draw_ts_in_day(self, day_index: int, profile: np.ndarray) -> int:
        hour = self._draw_hour(profile)
        minute = int(self.rng.integers(0, 60))
        second = int(self.rng.integers(0, 60))
        return _day_start_utc(day_index) + hour * 3600 + minute * 60 + second

    def _random_day(self, start_day: int, end_day: int) -> int:
        return int(self.rng.integers(start_day, end_day + 1))

    def _clamp_ts_span(self, indices: Sequence[int], ts: int) -> int:
        """Clamp a timestamp so it is valid for every listed customer.

        Fraud episodes happily pick a wall-clock instant that is valid for one
        participant but outside another's active window, or before an account
        was opened. Clamping into the intersection of the participants'
        windows (or, when they do not overlap, to the latest window start)
        keeps every emitted event causally coherent: no transaction is ever
        dated before its sender or receiver existed, and no transaction cites
        a device that has not yet been first seen.
        """
        starts = [_day_start_utc(int(self._cust_start_day[i])) for i in indices]
        ends = [
            _day_start_utc(int(self._cust_end_day[i]) + 1) - 1 for i in indices
        ]
        lo = max(starts)
        hi = max(lo, min(ends))
        return max(lo, min(int(ts), hi))

    def _clamp_ts_for(self, cust_idx: int, ts: int) -> int:
        """Clamp a timestamp into a single customer's activity window."""
        return self._clamp_ts_span([cust_idx], ts)

    @staticmethod
    def _day_of_ts(ts: int) -> int:
        """Return the synthetic day index containing a UTC epoch second."""
        return (int(ts) - SIM_START_UTC_EPOCH) // SECONDS_PER_DAY

    def _pick_customer(self, eligible_only: bool = True) -> int:
        pool = self._fraud_eligible if eligible_only else np.arange(len(self._cust_ids))
        return int(self.rng.choice(pool))

    def _pick_customer_alive(self, ts: int) -> int:
        """Pick a customer whose account already existed at ``ts``.

        Prevents a transaction ever naming a receiver that had not been opened
        yet, which would be both unrealistic and a causality violation.
        """
        hi = int(np.searchsorted(self._cust_created_sorted, int(ts), side="right"))
        if hi <= 0:
            return 0
        return int(self._cust_created_order[int(self.rng.integers(0, hi))])

    def _pick_alive_from(self, candidates: Sequence[int], ts: int) -> int:
        """Pick from a candidate set, restricted to accounts open at ``ts``."""
        alive = [c for c in candidates if int(self._cust_created[c]) <= int(ts)]
        pool = alive if alive else list(candidates)
        return int(pool[int(self.rng.integers(0, len(pool)))])

    def _pick_location_in_region(self, region_idx: int) -> Location:
        candidates = np.flatnonzero(self._loc_region == region_idx)
        return self.locations[int(self.rng.choice(candidates))]

    def _pick_location_other_region(self, region_idx: int) -> Location:
        others = np.flatnonzero(self._loc_region != region_idx)
        return self.locations[int(self.rng.choice(others))]

    def _pick_merchant(self, contacts: Sequence[int], kind: str | None = None) -> int:
        """Pick a merchant, preferring the customer's own merchant set."""
        pool = self._mer_kind_index.get(kind) if kind is not None else None
        if pool is None or len(pool) == 0:
            pool = np.arange(len(self._mer_ids), dtype=np.int64)
        if contacts:
            contact_pool = np.array(
                [m for m in contacts if kind is None or self._mer_kind[m] == kind],
                dtype=np.int64,
            )
            if len(contact_pool) > 0 and self.rng.random() < 0.72:
                return int(self.rng.choice(contact_pool))
        return int(self.rng.choice(pool))

    def _pick_agent(self, contacts: Sequence[int], region_idx: int) -> int:
        if contacts and self.rng.random() < 0.8:
            return int(self.rng.choice(np.asarray(contacts, dtype=np.int64)))
        same_region = np.flatnonzero(self._agt_region == region_idx)
        pool = same_region if len(same_region) else np.arange(len(self._agt_ids))
        return int(self.rng.choice(pool))

    # -- population construction -------------------------------------------

    def _build_merchants(self) -> None:
        n = self.cfg.n_merchants
        region_idx = self.rng.choice(
            len(REGIONS), size=n, p=np.array(REGION_WEIGHTS) / sum(REGION_WEIGHTS)
        )
        kinds = self.rng.choice(
            len(MERCHANT_KINDS),
            size=n,
            p=np.array(MERCHANT_KIND_WEIGHTS) / sum(MERCHANT_KIND_WEIGHTS),
        )
        now = SIM_START_UTC_EPOCH
        for i in range(n):
            merchant_id = self._next_identity("merchant", 4, "M")
            region = REGIONS[int(region_idx[i])]
            location = self._pick_location_in_region(int(region_idx[i]))
            created = now - int(self.rng.integers(120, 2400)) * SECONDS_PER_DAY
            size_band = str(
                self.rng.choice(["small", "medium", "large"], p=[0.45, 0.35, 0.20])
            )
            self._entity_rows.append(
                {
                    "entity_id": merchant_id,
                    "kind": "merchant",
                    "created_at": created,
                    "region": region,
                    "peer_group": f"merch|{region}|{size_band}",
                }
            )
            self._mer_ids.append(merchant_id)
            self._mer_kind.append(MERCHANT_KINDS[int(kinds[i])])
            self._mer_location = np.append(self._mer_location, self.locations.index(location))
            weight = {"small": 1.0, "medium": 3.2, "large": 9.0}[size_band]
            self._mer_weight = np.append(self._mer_weight, weight)
        self._mer_region = np.asarray(region_idx, dtype=np.int64)
        for kind in MERCHANT_KINDS:
            self._mer_kind_index[kind] = np.array(
                [i for i, k in enumerate(self._mer_kind) if k == kind], dtype=np.int64
            )

    def _build_agents(self) -> None:
        n = self.cfg.n_agents
        region_idx = self.rng.choice(
            len(REGIONS), size=n, p=np.array(REGION_WEIGHTS) / sum(REGION_WEIGHTS)
        )
        now = SIM_START_UTC_EPOCH
        for i in range(n):
            agent_id = self._next_identity("agent", 4, "A")
            region = REGIONS[int(region_idx[i])]
            location = self._pick_location_in_region(int(region_idx[i]))
            age_days = int(self.rng.integers(30, 1800))
            created = now - age_days * SECONDS_PER_DAY
            activity_band = str(self.rng.choice(["low", "mid", "high"], p=[0.4, 0.4, 0.2]))
            age_band = "new" if age_days < 180 else ("established" if age_days < 730 else "veteran")
            self._entity_rows.append(
                {
                    "entity_id": agent_id,
                    "kind": "agent",
                    "created_at": created,
                    "region": region,
                    "peer_group": f"agent|{region}|{activity_band}|{age_band}",
                }
            )
            self._agt_ids.append(agent_id)
            self._agt_location = np.append(self._agt_location, self.locations.index(location))
            device = self._mint_device(agent_id, created, CHANNEL_AGENT)
            self._agt_device.append(device)
            self._agt_weight = np.append(
                self._agt_weight, {"low": 1.0, "mid": 3.0, "high": 8.0}[activity_band]
            )
        self._agt_region = np.asarray(region_idx, dtype=np.int64)

    def _build_customers(self) -> None:
        n = self.cfg.n_wallets
        rng = self.rng
        region_idx = rng.choice(
            len(REGIONS), size=n, p=np.array(REGION_WEIGHTS) / sum(REGION_WEIGHTS)
        )
        # 8% of wallets are opened inside the synthetic window. These are the
        # accounts a mule or scam network would plausibly recruit.
        new_account = rng.random(n) < 0.08
        activity = rng.lognormal(mean=0.0, sigma=0.85, size=n)
        now = SIM_START_UTC_EPOCH
        total_days = self.cfg.days

        for i in range(n):
            customer_id = self._next_identity("customer", 6, "C")
            region = REGIONS[int(region_idx[i])]
            created_day = int(rng.integers(1, max(2, total_days // 2))) if new_account[i] else -1
            if new_account[i]:
                created = SIM_START_UTC_EPOCH + created_day * SECONDS_PER_DAY
                start_day = created_day
            else:
                created = now - int(rng.integers(30, 2600)) * SECONDS_PER_DAY
                start_day = 0
            # 14% of wallets become inactive part-way through the window; a
            # realistic churn pattern that also gives per-entity activity
            # windows genuinely different lengths.
            if rng.random() < 0.14:
                end_day = int(rng.integers(start_day + 1, total_days))
            else:
                end_day = total_days - 1
            end_day = max(end_day, start_day)

            band = "high" if activity[i] > 2.2 else ("mid" if activity[i] > 0.7 else "low")
            self._entity_rows.append(
                {
                    "entity_id": customer_id,
                    "kind": "customer",
                    "created_at": created,
                    "region": region,
                    "peer_group": f"cust|{region}|{band}",
                }
            )
            channel = CHANNEL_APP if rng.random() < 0.82 else CHANNEL_USSD
            device = self._mint_device(customer_id, created, channel)
            device2: str | None = None
            device2_day = -1
            # Benign device replacement: the account keeps working from a new
            # handset. This is the confounder that makes "new device" alone
            # meaningless as a fraud signal.
            if not new_account[i] and rng.random() < 0.22:
                replacement_day = int(rng.integers(1, total_days))
                device2 = self._mint_device(
                    customer_id,
                    SIM_START_UTC_EPOCH + replacement_day * SECONDS_PER_DAY,
                    channel,
                )
                device2_day = replacement_day

            profile = GLOBAL_HOUR_PROFILE
            if rng.random() < NIGHT_OWL_SHARE:
                profile = np.roll(GLOBAL_HOUR_PROFILE, 12)
            self._cust_ids.append(customer_id)
            self._cust_created = np.append(self._cust_created, created)
            self._cust_start_day = np.append(self._cust_start_day, start_day)
            self._cust_end_day = np.append(self._cust_end_day, end_day)
            self._cust_median = np.append(
                self._cust_median, float(self.rng.lognormal(mean=math.log(1500.0 * 100), sigma=0.6))
            )
            self._cust_device.append(device)
            self._cust_device2.append(device2)
            self._cust_device2_day = np.append(self._cust_device2_day, device2_day)
            self._cust_hour_profile.append(profile)
            self._cust_txn_count = np.append(self._cust_txn_count, 0)

        self._cust_region = np.asarray(region_idx, dtype=np.int64)
        self._cust_new_account = np.asarray(new_account, dtype=bool)
        self._cust_id_index = {cid: i for i, cid in enumerate(self._cust_ids)}
        # Sorted creation times let recipient selection cheaply restrict itself
        # to accounts that already existed at the transaction instant.
        self._cust_created_order = np.argsort(self._cust_created, kind="stable").astype(np.int64)
        self._cust_created_sorted = self._cust_created[self._cust_created_order]

        # Contacts: a customer's repeat recipients, region-biased, which makes
        # `recipient_is_new` a meaningful feature rather than noise.
        region_weight = np.ones((n, n), dtype=float)
        same = self._cust_region[:, None] == self._cust_region[None, :]
        region_weight[same] = 4.0
        np.fill_diagonal(region_weight, 0.0)
        for i in range(n):
            k = int(rng.integers(2, 26))
            p = region_weight[i] / region_weight[i].sum()
            self._cust_contacts.append([int(x) for x in rng.choice(n, size=k, replace=False, p=p)])
            m = int(rng.integers(2, 5))
            self._cust_merchants.append(
                [int(x) for x in rng.choice(len(self._mer_ids), size=m, replace=False)]
            )
            same_agents = np.flatnonzero(self._agt_region == region_idx[i])
            a = min(int(rng.integers(1, 4)), len(same_agents))
            self._cust_agents.append(
                [int(x) for x in rng.choice(same_agents, size=a, replace=False)]
            )

        # Customers eligible to star in a fraud episode: enough history to
        # have a personal baseline and a long enough activity window.
        span = self._cust_end_day - self._cust_start_day
        eligible = np.flatnonzero((span >= 5) & (~new_account | (span >= 3)))
        if len(eligible) == 0:
            eligible = np.arange(n, dtype=np.int64)
        self._fraud_eligible = eligible.astype(np.int64)

    # -- ordinary behaviour -------------------------------------------------

    def _emit_customer_transaction(self, cust_idx: int, day: int) -> None:
        """Emit one ordinary outgoing transaction for a customer."""
        rng = self.rng
        region_idx = int(self._cust_region[cust_idx])
        profile = self._cust_hour_profile[cust_idx]
        ts = self._draw_ts_in_day(max(day, int(self._cust_start_day[cust_idx])), profile)
        txn_type = str(
            rng.choice(
                [TYPE_SEND, TYPE_CASH_OUT, TYPE_MERCHANT, TYPE_BILL, TYPE_RECHARGE],
                p=[0.26, 0.21, 0.22, 0.13, 0.18],
            )
        )
        amount = _draw_amount(rng, txn_type, scale=1.0)
        if rng.random() < BENIGN_LARGE_SHARE:
            lo, hi = BENIGN_LARGE_FACTOR
            amount = _round_amount(amount * float(rng.uniform(lo, hi)), rng)
        device = self._device_for(cust_idx, day)
        location = self._location_for(cust_idx)
        contacts = self._cust_contacts[cust_idx]

        if txn_type == TYPE_SEND:
            if rng.random() < 0.28:
                receiver = self._pick_customer_alive(ts)
            else:
                receiver = self._pick_alive_from(contacts, ts)
            if receiver == cust_idx:
                receiver = self._pick_customer_alive(ts)
            if receiver == cust_idx:
                receiver = (cust_idx + 1) % len(self._cust_ids)
            self._add_txn(
                sender_id=self._cust_ids[cust_idx],
                receiver_id=self._cust_ids[receiver],
                amount_poisha=amount,
                txn_type=txn_type,
                timestamp=ts,
                device_id=device,
                location_id=location.location_id,
            )
            return

        if txn_type == TYPE_CASH_OUT:
            agent_idx = self._pick_agent(self._cust_agents[cust_idx], region_idx)
            self._add_txn(
                sender_id=self._cust_ids[cust_idx],
                receiver_id=self._agt_ids[agent_idx],
                amount_poisha=amount,
                txn_type=txn_type,
                timestamp=ts,
                device_id=device,
                location_id=location.location_id,
            )
            return

        kind = None
        if txn_type == TYPE_BILL:
            kind = BILLER_KIND
        elif txn_type == TYPE_RECHARGE:
            kind = TELCO_KIND
        merchant_idx = self._pick_merchant(self._cust_merchants[cust_idx], kind)
        self._add_txn(
            sender_id=self._cust_ids[cust_idx],
            receiver_id=self._mer_ids[merchant_idx],
            amount_poisha=amount,
            txn_type=txn_type,
            timestamp=ts,
            device_id=device,
            location_id=location.location_id,
        )

    def _device_for(self, cust_idx: int, day: int) -> str:
        """Return the device a customer would use on a given day.

        A replacement handset is only ever returned on or after its
        ``first_seen_at`` day, so no transaction ever cites a device that did
        not yet exist. That keeps the generated history causally coherent.
        """
        second = self._cust_device2[cust_idx]
        if (
            second is not None
            and day >= int(self._cust_device2_day[cust_idx])
            and self.rng.random() < 0.6
        ):
            return second
        return self._cust_device[cust_idx]

    def _location_for(self, cust_idx: int) -> Location:
        """Return a location for an ordinary event.

        Mostly home, sometimes another area in the same region, and rarely
        another region — the ordinary travel that makes raw distance a weak
        signal on its own.
        """
        region_idx = int(self._cust_region[cust_idx])
        draw = self.rng.random()
        if draw < 0.86:
            return self.locations[int(self.rng.choice(np.flatnonzero(self._loc_region == region_idx)))]
        if draw < 0.98:
            return self._pick_location_in_region(region_idx)
        return self._pick_location_other_region(region_idx)

    def _generate_customer_activity(self, target: int) -> None:
        """Generate ``target`` ordinary customer-sent transactions."""
        n = len(self._cust_ids)
        if target <= 0:
            return
        weights = self.rng.lognormal(mean=0.0, sigma=0.85, size=n)
        allocated = _largest_remainder(weights, target)
        for i in range(n):
            count = int(allocated[i])
            if count == 0:
                continue
            days = self.rng.integers(
                int(self._cust_start_day[i]), int(self._cust_end_day[i]) + 1, size=count
            )
            days = np.sort(days, kind="stable")
            for d in days:
                self._emit_customer_transaction(i, int(d))

    def _generate_agent_flows(self, n_cash_in: int, n_settlement: int) -> None:
        """Generate agent-originated flows: cash-in and settlement."""
        rng = self.rng
        for _ in range(max(n_cash_in, 0)):
            agent_idx = int(rng.choice(len(self._agt_ids), p=self._agt_weight / self._agt_weight.sum()))
            cust_idx = self._pick_customer(eligible_only=False)
            day = self._random_day(
                int(self._cust_start_day[cust_idx]), int(self._cust_end_day[cust_idx])
            )
            ts = self._draw_ts_in_day(day, self._cust_hour_profile[cust_idx])
            amount = _draw_amount(rng, TYPE_CASH_IN)
            self._add_txn(
                sender_id=self._agt_ids[agent_idx],
                receiver_id=self._cust_ids[cust_idx],
                amount_poisha=amount,
                txn_type=TYPE_CASH_IN,
                timestamp=ts,
                device_id=self._agt_device[agent_idx],
                location_id=self._agt_location_id(agent_idx),
            )
        for _ in range(max(n_settlement, 0)):
            a = int(rng.choice(len(self._agt_ids)))
            b = int(rng.choice(len(self._agt_ids)))
            if b == a:
                b = (a + 1) % len(self._agt_ids)
            day = self._random_day(0, self.cfg.days - 1)
            ts = self._draw_ts_in_day(day, GLOBAL_HOUR_PROFILE)
            amount = _draw_amount(rng, TYPE_SETTLEMENT)
            self._add_txn(
                sender_id=self._agt_ids[a],
                receiver_id=self._agt_ids[b],
                amount_poisha=amount,
                txn_type=TYPE_SETTLEMENT,
                timestamp=ts,
                device_id=self._agt_device[a],
                location_id=self._agt_location_id(a),
            )

    def _agt_location_id(self, agent_idx: int) -> str:
        return self.locations[int(self._agt_location[agent_idx])].location_id

    # -- fraud episodes -----------------------------------------------------

    def _episode_severity(self, magnitude: float, subtle: bool) -> str:
        if subtle:
            return "low" if magnitude < 1.5 else "medium"
        if magnitude < 1.6:
            return "low"
        if magnitude < 3.0:
            return "medium"
        return "high"

    def _generate_fraud_episodes(self, budget: int) -> int:
        """Generate every fraud family and return the realised fraud count."""
        before = sum(1 for row in self._truth if row["is_fraud"])
        for family, share, mean_size in FRAUD_FAMILIES:
            allocation = budget * share
            n_episodes = max(1, int(round(allocation / mean_size)))
            generator = getattr(self, f"_episode_{family}")
            for _ in range(n_episodes):
                generator(mean_size)
        after = sum(1 for row in self._truth if row["is_fraud"])
        return after - before

    def _episode_ato(self, mean_size: float) -> None:
        """Account takeover: failed logins, unseen device, new payee, large pay."""
        rng = self.rng
        victim = self._pick_customer()
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        day = self._random_day(int(self._cust_start_day[victim]), int(self._cust_end_day[victim]))
        if subtle:
            base_ts = self._draw_ts_in_day(day, self._cust_hour_profile[victim])
        else:
            # Takeovers cluster in the small hours, but not exclusively.
            night = np.roll(GLOBAL_HOUR_PROFILE, 12)
            base_ts = self._draw_ts_in_day(day, night if rng.random() < 0.6 else GLOBAL_HOUR_PROFILE)
        # Leave room for the preceding failed logins inside the victim's window.
        base_ts = max(base_ts, _day_start_utc(int(self._cust_start_day[victim])) + 6 * 3600)

        region_idx = int(self._cust_region[victim])
        if subtle:
            takeover_location = self._pick_location_in_region(region_idx)
        elif rng.random() < 0.7:
            takeover_location = self._pick_location_other_region(region_idx)
        else:
            takeover_location = self._pick_location_in_region(region_idx)

        device = self._mint_device(self._cust_ids[victim], base_ts - 3_600, CHANNEL_APP)
        n_failed = int(rng.integers(2, 7))
        for i in range(n_failed):
            self._add_login(
                entity_id=self._cust_ids[victim],
                timestamp=base_ts - (n_failed - i) * int(rng.integers(45, 400)),
                device_id=device,
                success=False,
                location_id=takeover_location.location_id,
            )
        self._add_login(
            entity_id=self._cust_ids[victim],
            timestamp=base_ts - int(rng.integers(10, 240)),
            device_id=device,
            success=True,
            location_id=takeover_location.location_id,
        )

        n_out = max(1, int(round(float(rng.normal(mean_size * 0.6, 1.0)))))
        n_out = min(n_out, 4)
        median = float(self._cust_median[victim])
        contacts = set(self._cust_contacts[victim])
        for j in range(n_out):
            ts = self._clamp_ts_for(victim, base_ts + j * int(rng.integers(45, 900)))
            if subtle:
                factor = float(math.exp(rng.normal(0.1, 0.3)))
                recipient = self._pick_alive_from(self._cust_contacts[victim], ts)
            else:
                factor = float(math.exp(rng.normal(0.95, 0.75)))
                recipient = self._pick_customer_alive(ts)
                guard = 0
                while recipient in contacts and guard < 20:
                    recipient = self._pick_customer_alive(ts)
                    guard += 1
            if recipient == victim:
                recipient = self._pick_customer_alive(ts)
            if recipient == victim:
                recipient = (victim + 1) % len(self._cust_ids)
            amount = _round_amount(min(median * factor, 40_000.0 * 100), rng)
            amount = max(amount, 5_000)
            severity = self._episode_severity(factor, subtle)
            self._add_txn(
                sender_id=self._cust_ids[victim],
                receiver_id=self._cust_ids[recipient],
                amount_poisha=amount,
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=device,
                location_id=takeover_location.location_id,
                status="completed" if rng.random() > 0.12 else "failed",
                is_fraud=True,
                fraud_family="ato",
                severity=severity,
            )

    def _episode_velocity_burst(self, mean_size: float) -> None:
        """Many small transfers, then one larger attempt, inside one window."""
        rng = self.rng
        sender = self._pick_customer()
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        day = self._random_day(int(self._cust_start_day[sender]), int(self._cust_end_day[sender]))
        start = self._draw_ts_in_day(day, self._cust_hour_profile[sender])
        n_small = max(2, int(round(float(rng.normal(mean_size * 0.75, 1.5)))))
        n_small = min(n_small, 9)
        gap = int(rng.integers(120, 1_800 if subtle else 420))
        median = float(self._cust_median[sender])
        contacts = np.asarray(self._cust_contacts[sender], dtype=np.int64)
        device = self._device_for(sender, day)
        location = self._location_for(sender)

        for j in range(n_small):
            ts = self._clamp_ts_for(sender, start + j * gap)
            if subtle and rng.random() < 0.7:
                recipient = self._pick_alive_from(contacts, ts)
            else:
                recipient = self._pick_customer_alive(ts)
            if recipient == sender:
                recipient = self._pick_customer_alive(ts)
            if recipient == sender:
                recipient = (sender + 1) % len(self._cust_ids)
            amount = _round_amount(median * float(rng.uniform(0.10, 0.55)), rng)
            self._add_txn(
                sender_id=self._cust_ids[sender],
                receiver_id=self._cust_ids[recipient],
                amount_poisha=max(amount, 1_000),
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=device,
                location_id=location.location_id,
                is_fraud=True,
                fraud_family="velocity_burst",
                severity="medium" if not subtle else "low",
            )

        factor = float(rng.uniform(1.4, 2.3)) if subtle else float(rng.uniform(2.6, 6.0))
        big = _round_amount(min(median * factor, 50_000.0 * 100), rng)
        big_ts = self._clamp_ts_for(sender, start + n_small * gap + int(rng.integers(60, 600)))
        recipient = (
            self._pick_alive_from(contacts, big_ts)
            if subtle and rng.random() < 0.5
            else self._pick_customer_alive(big_ts)
        )
        if recipient == sender:
            recipient = self._pick_customer_alive(big_ts)
        if recipient == sender:
            recipient = (sender + 1) % len(self._cust_ids)
        self._add_txn(
            sender_id=self._cust_ids[sender],
            receiver_id=self._cust_ids[recipient],
            amount_poisha=max(big, 5_000),
            txn_type=TYPE_SEND,
            timestamp=big_ts,
            device_id=device,
            location_id=location.location_id,
            status="failed" if rng.random() < 0.28 else "completed",
            is_fraud=True,
            fraud_family="velocity_burst",
            severity=self._episode_severity(factor, subtle),
        )

    def _episode_mule_fanin(self, mean_size: float) -> None:
        """Fan-in from many senders, then a fast pass-through or cash-out."""
        rng = self.rng
        # Prefer a recently opened account as the collection point.
        new_pool = np.flatnonzero(self._cust_new_account)
        mule = int(rng.choice(new_pool)) if len(new_pool) else self._pick_customer()
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        span_hours = int(rng.integers(6, 24)) if subtle else int(rng.integers(24, 96))
        base_day = self._random_day(0, max(0, self.cfg.days - 3))
        start = _day_start_utc(base_day) + int(rng.integers(0, 20)) * 3600
        n_in = max(2, int(round(float(rng.normal(mean_size * 0.65, 1.6)))))
        n_in = min(n_in, 12)
        total = 0
        latest = start
        mule_total_before = float(self._cust_median[mule])
        for j in range(n_in):
            sender = self._pick_customer(eligible_only=False)
            if sender == mule:
                sender = (mule + 1) % len(self._cust_ids)
            ts = self._clamp_ts_span(
                [sender, mule],
                start + j * int(rng.integers(600, max(700, span_hours * 3_600 // max(n_in, 1)))),
            )
            amount = _draw_amount(
                rng, TYPE_SEND, scale=float(rng.uniform(0.6, 2.4)), sigma=0.6
            )
            self._add_txn(
                sender_id=self._cust_ids[sender],
                receiver_id=self._cust_ids[mule],
                amount_poisha=amount,
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=self._device_for(sender, self._day_of_ts(ts)),
                location_id=self._location_for(sender).location_id,
                is_fraud=True,
                fraud_family="mule_fanin",
                severity="medium" if subtle else "high",
            )
            total += amount
            latest = max(latest, ts)

        pass_amount = _round_amount(total * float(rng.uniform(0.80, 0.97)), rng)
        out_ts = self._clamp_ts_for(mule, latest + int(rng.integers(300, 10_800)))
        if rng.random() < 0.6 or pass_amount > mule_total_before * 3:
            agent_idx = self._pick_agent(self._cust_agents[mule], int(self._cust_region[mule]))
            self._add_txn(
                sender_id=self._cust_ids[mule],
                receiver_id=self._agt_ids[agent_idx],
                amount_poisha=max(pass_amount, 10_000),
                txn_type=TYPE_CASH_OUT,
                timestamp=out_ts,
                device_id=self._device_for(mule, self._day_of_ts(out_ts)),
                location_id=self._location_for(mule).location_id,
                is_fraud=True,
                fraud_family="mule_fanin",
                severity="medium" if subtle else "high",
            )
        else:
            outlet = self._pick_customer_alive(out_ts)
            if outlet == mule:
                outlet = (mule + 1) % len(self._cust_ids)
            self._add_txn(
                sender_id=self._cust_ids[mule],
                receiver_id=self._cust_ids[outlet],
                amount_poisha=max(pass_amount, 10_000),
                txn_type=TYPE_SEND,
                timestamp=out_ts,
                device_id=self._device_for(mule, self._day_of_ts(out_ts)),
                location_id=self._location_for(mule).location_id,
                is_fraud=True,
                fraud_family="mule_fanin",
                severity="medium" if subtle else "high",
            )

    def _episode_circular(self, mean_size: float) -> None:
        """A short cycle of transfers inside a bounded time window."""
        rng = self.rng
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        ring_size = 3 if rng.random() < 0.7 else 2
        base_day = self._random_day(0, max(0, self.cfg.days - 2))
        base_ts = _day_start_utc(base_day) + int(rng.integers(6, 22)) * 3600
        start_idx = self._pick_customer_alive(base_ts)
        ring = [start_idx]
        contacts = self._cust_contacts[start_idx]
        for _ in range(ring_size - 1):
            candidate = self._pick_alive_from(contacts, base_ts)
            if candidate in ring:
                candidate = self._pick_customer_alive(base_ts)
            if candidate in ring:
                candidate = (ring[-1] + 1 + int(rng.integers(0, 5))) % len(self._cust_ids)
            ring.append(candidate)
        ts = base_ts
        base_amount = _draw_amount(rng, TYPE_SEND, scale=float(rng.uniform(0.8, 2.0)))
        window = int(rng.integers(6, 48)) * 3600 if not subtle else int(rng.integers(24, 120)) * 3600
        leg_gap = max(600, window // ring_size)
        amount = float(base_amount)
        for j in range(ring_size):
            src = ring[j]
            dst = ring[(j + 1) % ring_size]
            amount *= float(rng.uniform(0.90, 0.995))
            ts = self._clamp_ts_span([src, dst], ts + int(rng.integers(600, leg_gap)))
            self._add_txn(
                sender_id=self._cust_ids[src],
                receiver_id=self._cust_ids[dst],
                amount_poisha=max(_round_amount(amount, rng), 1_000),
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=self._device_for(src, self._day_of_ts(ts)),
                location_id=self._location_for(src).location_id,
                is_fraud=True,
                fraud_family="circular",
                severity="low" if subtle else "medium",
            )

    def _episode_agent_cashout_spike(self, mean_size: float) -> None:
        """An agent's cash-out volume bursts above its own and its peers' norm."""
        rng = self.rng
        agent_idx = int(
            rng.choice(len(self._agt_ids), p=self._agt_weight / self._agt_weight.sum())
        )
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        base_day = self._random_day(0, self.cfg.days - 1)
        start = _day_start_utc(base_day) + int(rng.integers(7, 16)) * 3600
        n_extra = max(2, int(round(float(rng.normal(mean_size * (0.5 if subtle else 1.0), 2.0)))))
        n_extra = min(n_extra, 22)
        gap = int(rng.integers(120, 900))
        region_idx = int(self._agt_region[agent_idx])
        for j in range(n_extra):
            cust_idx = int(
                rng.choice(np.flatnonzero(self._cust_region == region_idx))
            )
            ts = self._clamp_ts_for(cust_idx, start + j * gap)
            amount = _draw_amount(rng, TYPE_CASH_OUT, scale=1.0)
            self._add_txn(
                sender_id=self._cust_ids[cust_idx],
                receiver_id=self._agt_ids[agent_idx],
                amount_poisha=amount,
                txn_type=TYPE_CASH_OUT,
                timestamp=ts,
                device_id=self._device_for(cust_idx, self._day_of_ts(ts)),
                location_id=self._agt_location_id(agent_idx),
                is_fraud=True,
                fraud_family="agent_cashout_spike",
                severity="low" if subtle else "medium",
            )

    def _episode_scam_escalation(self, mean_size: float) -> None:
        """New beneficiary plus repeated, escalating transfers."""
        rng = self.rng
        victim = self._pick_customer()
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        n = max(2, int(round(float(rng.normal(mean_size, 1.2)))))
        n = min(n, 7)
        contacts = set(self._cust_contacts[victim])
        day = self._random_day(int(self._cust_start_day[victim]), int(self._cust_end_day[victim]))
        ts = self._draw_ts_in_day(day, self._cust_hour_profile[victim])
        recipient = self._pick_customer_alive(ts)
        guard = 0
        while recipient in contacts and guard < 25:
            recipient = self._pick_customer_alive(ts)
            guard += 1
        if recipient == victim:
            recipient = self._pick_customer_alive(ts)
        if recipient == victim:
            recipient = (victim + 1) % len(self._cust_ids)
        median = float(self._cust_median[victim])
        amount = median * float(rng.uniform(0.4, 1.1))
        ratio_lo, ratio_hi = (1.12, 1.45) if subtle else (1.45, 2.5)
        for _ in range(n):
            amount *= float(rng.uniform(ratio_lo, ratio_hi))
            ts = self._clamp_ts_for(victim, ts + int(rng.integers(4, 20)) * 3_600)
            self._add_txn(
                sender_id=self._cust_ids[victim],
                receiver_id=self._cust_ids[recipient],
                amount_poisha=max(_round_amount(min(amount, 60_000.0 * 100), rng), 5_000),
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=self._device_for(victim, self._day_of_ts(ts)),
                location_id=self._location_for(victim).location_id,
                is_fraud=True,
                fraud_family="scam_escalation",
                severity="low" if subtle else "medium",
            )

    def _episode_scam_split(self, mean_size: float) -> None:
        """One beneficiary paid many similar amounts inside a short window."""
        rng = self.rng
        victim = self._pick_customer()
        subtle = rng.random() < SUBTLE_EPISODE_SHARE
        n = max(3, int(round(float(rng.normal(mean_size, 2.0)))))
        n = min(n, 14)
        contacts = set(self._cust_contacts[victim])
        day = self._random_day(int(self._cust_start_day[victim]), int(self._cust_end_day[victim]))
        start = self._draw_ts_in_day(day, self._cust_hour_profile[victim])
        recipient = self._pick_customer_alive(start)
        guard = 0
        while recipient in contacts and guard < 25:
            recipient = self._pick_customer_alive(start)
            guard += 1
        if recipient == victim:
            recipient = self._pick_customer_alive(start)
        if recipient == victim:
            recipient = (victim + 1) % len(self._cust_ids)
        base = float(self._cust_median[victim]) * float(rng.uniform(0.5, 1.4))
        span = int(rng.integers(1_800, 10_800)) if not subtle else int(rng.integers(10_800, 86_400))
        for j in range(n):
            amount = base * float(rng.uniform(0.88, 1.12))
            ts = self._clamp_ts_for(
                victim, start + int(j * span / n) + int(rng.integers(1, 90))
            )
            self._add_txn(
                sender_id=self._cust_ids[victim],
                receiver_id=self._cust_ids[recipient],
                amount_poisha=max(_round_amount(amount, rng), 1_000),
                txn_type=TYPE_SEND,
                timestamp=ts,
                device_id=self._device_for(victim, self._day_of_ts(ts)),
                location_id=self._location_for(victim).location_id,
                is_fraud=True,
                fraud_family="scam_split",
                severity="low" if subtle else "medium",
            )

    # -- benign confounders -------------------------------------------------

    def _generate_confounders(self) -> int:
        """Inject legitimate behaviour that mimics fraud. Returns row count."""
        before = len(self._truth)
        rng = self.rng
        # 1. Salary day: payday inflows followed by a burst of ordinary spending.
        salary_days = [
            d for d in range(self.cfg.days) if _local_date(d).day in (1, 25)
        ]
        n_salary_recipients = max(4, int(len(self._cust_ids) * 0.10))
        for day in salary_days:
            recipients = rng.choice(len(self._cust_ids), size=n_salary_recipients, replace=False)
            for idx in recipients:
                i = int(idx)
                if not (self._cust_start_day[i] <= day <= self._cust_end_day[i]):
                    continue
                salary_ts = _day_start_utc(day) + int(rng.integers(8, 12)) * 3600
                salary_amount = _round_amount(float(rng.normal(28_000, 8_000)) * 100, rng)
                agent_idx = self._pick_agent(self._cust_agents[i], int(self._cust_region[i]))
                self._add_txn(
                    sender_id=self._agt_ids[agent_idx],
                    receiver_id=self._cust_ids[i],
                    amount_poisha=max(salary_amount, 100_000),
                    txn_type=TYPE_CASH_IN,
                    timestamp=salary_ts,
                    device_id=self._agt_device[agent_idx],
                    location_id=self._agt_location_id(agent_idx),
                    confounder_family="salary_day_spike",
                )
                n_spend = int(rng.integers(2, 7))
                for _ in range(n_spend):
                    spend_ts = self._clamp_ts_for(
                        i, salary_ts + int(rng.integers(300, 10_800))
                    )
                    txn_type = str(
                        rng.choice(
                            [TYPE_SEND, TYPE_CASH_OUT, TYPE_MERCHANT],
                            p=[0.35, 0.35, 0.30],
                        )
                    )
                    amount = _draw_amount(rng, txn_type, scale=1.0)
                    if txn_type == TYPE_CASH_OUT:
                        receiver = self._agt_ids[
                            self._pick_agent(self._cust_agents[i], int(self._cust_region[i]))
                        ]
                    elif txn_type == TYPE_SEND:
                        receiver = self._cust_ids[
                            self._pick_alive_from(self._cust_contacts[i], spend_ts)
                        ]
                    else:
                        receiver = self._mer_ids[self._pick_merchant(self._cust_merchants[i])]
                    self._add_txn(
                        sender_id=self._cust_ids[i],
                        receiver_id=receiver,
                        amount_poisha=amount,
                        txn_type=txn_type,
                        timestamp=spend_ts,
                        device_id=self._device_for(i, day),
                        location_id=self._location_for(i).location_id,
                        confounder_family="salary_day_spike",
                    )

        # 2. Legitimate bulk receipts: a merchant gets many genuine payments in
        #    a short window (festival sales, tuition collection, and so on).
        n_bulk_merchants = max(2, int(len(self._mer_ids) * 0.2))
        for m in rng.choice(len(self._mer_ids), size=n_bulk_merchants, replace=False):
            merchant_idx = int(m)
            day = self._random_day(0, self.cfg.days - 1)
            start = _day_start_utc(day) + int(rng.integers(8, 15)) * 3600
            n_payments = int(rng.integers(12, 60))
            senders = rng.choice(len(self._cust_ids), size=n_payments, replace=True)
            for j, s in enumerate(senders):
                sender_idx = int(s)
                ts = self._clamp_ts_for(sender_idx, start + j * int(rng.integers(60, 420)))
                amount = _draw_amount(rng, TYPE_MERCHANT, scale=1.0)
                self._add_txn(
                    sender_id=self._cust_ids[sender_idx],
                    receiver_id=self._mer_ids[merchant_idx],
                    amount_poisha=amount,
                    txn_type=TYPE_MERCHANT,
                    timestamp=ts,
                    device_id=self._device_for(sender_idx, self._day_of_ts(ts)),
                    location_id=self.locations[int(self._mer_location[merchant_idx])].location_id,
                    confounder_family="bulk_merchant_receipts",
                )

        # 3. Benign travel: new device and a distant location, but ordinary
        #    spending spread over days so travel time stays plausible.
        n_travellers = max(2, int(len(self._cust_ids) * 0.05))
        for t in rng.choice(len(self._cust_ids), size=n_travellers, replace=False):
            i = int(t)
            day = self._random_day(int(self._cust_start_day[i]), int(self._cust_end_day[i]))
            travel_location = self._pick_location_other_region(int(self._cust_region[i]))
            device = self._mint_device(
                self._cust_ids[i], _day_start_utc(day), CHANNEL_APP
            )
            self._add_login(
                entity_id=self._cust_ids[i],
                timestamp=_day_start_utc(day) + int(rng.integers(6, 10)) * 3600,
                device_id=device,
                success=True,
                location_id=travel_location.location_id,
            )
            n_spend = int(rng.integers(2, 7))
            for j in range(n_spend):
                ts = _day_start_utc(day) + int(rng.integers(9, 21)) * 3600 + j * 3_600
                txn_type = str(rng.choice([TYPE_MERCHANT, TYPE_CASH_OUT, TYPE_SEND], p=[0.5, 0.3, 0.2]))
                amount = _draw_amount(rng, txn_type, scale=1.0)
                if txn_type == TYPE_CASH_OUT:
                    receiver = self._agt_ids[self._pick_agent([], int(self._cust_region[i]))]
                elif txn_type == TYPE_SEND:
                    receiver = self._cust_ids[
                        self._pick_alive_from(self._cust_contacts[i], ts)
                    ]
                else:
                    receiver = self._mer_ids[self._pick_merchant(self._cust_merchants[i])]
                self._add_txn(
                    sender_id=self._cust_ids[i],
                    receiver_id=receiver,
                    amount_poisha=amount,
                    txn_type=txn_type,
                    timestamp=ts,
                    device_id=device,
                    location_id=travel_location.location_id,
                    confounder_family="travel_new_device",
                )
        return len(self._truth) - before

    # -- logins -------------------------------------------------------------

    def _generate_logins(self) -> None:
        """Routine authentication history for every customer."""
        rng = self.rng
        for i, customer_id in enumerate(self._cust_ids):
            n = int(self._cust_txn_count[i])
            n_logins = max(1, int(round(n * 1.25 + float(rng.normal(0, 1.5)))))
            n_logins = min(n_logins, 400)
            offset = int(rng.integers(-3, 4))
            profile = np.roll(self._cust_hour_profile[i], offset)
            for _ in range(n_logins):
                day = self._random_day(
                    int(self._cust_start_day[i]), int(self._cust_end_day[i])
                )
                ts = self._draw_ts_in_day(day, profile)
                success = rng.random() > 0.09
                device = self._device_for(i, day)
                location = self._location_for(i)
                self._add_login(
                    entity_id=customer_id,
                    timestamp=ts,
                    device_id=device,
                    success=bool(success),
                    location_id=location.location_id,
                )
        for agent_idx, agent_id in enumerate(self._agt_ids):
            device = self._agt_device[agent_idx]
            for _ in range(int(rng.integers(1, 4))):
                day = self._random_day(0, self.cfg.days - 1)
                self._add_login(
                    entity_id=agent_id,
                    timestamp=self._draw_ts_in_day(day, GLOBAL_HOUR_PROFILE),
                    device_id=device,
                    success=bool(rng.random() > 0.04),
                    location_id=self._agt_location_id(agent_idx),
                )

    # -- finalisation -------------------------------------------------------

    def _finalise(self) -> World:
        txns = pd.DataFrame(self._txns)
        truth = pd.DataFrame(self._truth)

        # Deterministic chronological order. `_uid` breaks ties so the order is
        # total and stable even for identical timestamps.
        txns = txns.sort_values(["timestamp", "_uid"], kind="stable").reset_index(drop=True)
        txns["id"] = [f"TX{i + 1:08d}" for i in range(len(txns))]
        txns["scenario_run_id"] = self.run_id

        truth = truth.set_index("_uid").loc[txns["_uid"].tolist()].reset_index()
        truth["transaction_id"] = txns["id"].tolist()
        truth["scenario_run_id"] = self.run_id

        transactions = txns[
            [
                "id",
                "sender_id",
                "receiver_id",
                "amount_poisha",
                "type",
                "timestamp",
                "device_id",
                "location",
                "status",
                "scenario_run_id",
            ]
        ].copy()
        transactions["timestamp"] = pd.to_datetime(transactions["timestamp"], unit="s", utc=True)
        transactions["amount_poisha"] = transactions["amount_poisha"].astype(np.int64)

        scenario_truth = truth[
            [
                "transaction_id",
                "scenario_run_id",
                "is_fraud",
                "fraud_family",
                "confounder_family",
                "scenario_severity",
            ]
        ].copy()
        scenario_truth["is_fraud"] = scenario_truth["is_fraud"].astype(bool)

        entities = pd.DataFrame(self._entity_rows)
        entities = entities.sort_values("entity_id", kind="stable").reset_index(drop=True)
        entities["created_at"] = pd.to_datetime(entities["created_at"], unit="s", utc=True)

        devices = pd.DataFrame(self._device_rows)
        devices = devices.sort_values("device_id", kind="stable").reset_index(drop=True)
        devices["first_seen_at"] = pd.to_datetime(devices["first_seen_at"], unit="s", utc=True)

        logins = pd.DataFrame(self._logins)
        logins = logins.sort_values(["timestamp", "entity_id"], kind="stable").reset_index(drop=True)
        logins["timestamp"] = pd.to_datetime(logins["timestamp"], unit="s", utc=True)

        locations = pd.DataFrame(
            [
                {
                    "location_id": loc.location_id,
                    "region": loc.region,
                    "area": loc.area,
                    "latitude": loc.latitude,
                    "longitude": loc.longitude,
                }
                for loc in self.locations
            ]
        )

        family_counts = (
            scenario_truth.loc[scenario_truth["is_fraud"], "fraud_family"]
            .value_counts()
            .to_dict()
        )
        confounder_counts = (
            scenario_truth.loc[
                scenario_truth["confounder_family"].notna(), "confounder_family"
            ]
            .value_counts()
            .to_dict()
        )
        n_fraud = int(scenario_truth["is_fraud"].sum())
        n_total = int(len(scenario_truth))

        stats: dict[str, object] = {
            "generator_version": GENERATOR_VERSION,
            "seed": self.cfg.seed,
            "scenario_run_id": self.run_id,
            "class_mix": {
                "fraud": n_fraud,
                "normal": n_total - n_fraud,
                "fraud_rate": round(n_fraud / n_total, 6) if n_total else 0.0,
                "fraud_budget_share": FRAUD_SHARE,
            },
            "fraud_families": {str(k): int(v) for k, v in family_counts.items()},
            "benign_confounders": {str(k): int(v) for k, v in confounder_counts.items()},
            "row_counts": {
                "entities": int(len(entities)),
                "devices": int(len(devices)),
                "transactions": int(len(transactions)),
                "login_events": int(len(logins)),
                "scenario_truth": int(len(scenario_truth)),
                "locations": int(len(locations)),
            },
            "entity_kinds": {
                str(k): int(v)
                for k, v in entities["kind"].value_counts().sort_index().items()
            },
            "time_range": {
                "start_utc": pd.Timestamp(
                    _day_start_utc(0), unit="s", tz="UTC"
                ).isoformat(),
                "end_utc": pd.Timestamp(
                    _day_start_utc(self.cfg.days) - 1, unit="s", tz="UTC"
                ).isoformat(),
                "local_start": SIM_START_LOCAL_DATE.isoformat(),
                "days": self.cfg.days,
            },
            "config": {
                "wallets": self.cfg.n_wallets,
                "merchants": self.cfg.n_merchants,
                "agents": self.cfg.n_agents,
                "transactions_requested": self.cfg.n_transactions,
                "days": self.cfg.days,
            },
        }
        return World(
            config=self.cfg,
            run_id=self.run_id,
            entities=entities,
            devices=devices,
            transactions=transactions,
            login_events=logins,
            scenario_truth=scenario_truth,
            locations=locations,
            stats=stats,
        )

    # -- orchestration ------------------------------------------------------

    def build(self) -> World:
        """Build the complete world."""
        n_total = self.cfg.n_transactions
        self._build_merchants()
        self._build_agents()
        self._build_customers()

        budget = int(round(n_total * FRAUD_SHARE))
        n_fraud = self._generate_fraud_episodes(budget)
        n_confounder = self._generate_confounders()

        n_cash_in = int(round(n_total * 0.04))
        n_settlement = int(round(n_total * 0.03))
        n_ordinary = max(0, n_total - n_fraud - n_confounder - n_cash_in - n_settlement)

        self._generate_agent_flows(n_cash_in, n_settlement)
        self._generate_customer_activity(n_ordinary)

        # Logins are generated last so that routine logins reflect the realised
        # activity per customer, not the pre-allocation estimate.
        self._generate_logins()
        return self._finalise()


def build_world(config: SimConfig) -> World:
    """Build one synthetic world from ``config``.

    Args:
        config: The generation configuration.

    Returns:
        A fully materialised :class:`World`.
    """
    return WorldBuilder(config).build()
