"""The synthetic transaction ledger.

Money is integer **poisha** everywhere (``BigInteger``). Timestamps are
timezone-aware UTC. Nothing here is a real payment: the whole ledger is
generated by the simulator and consumed by the scoring pipeline.
"""

from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    BigInteger,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import (
    ID_LENGTH,
    TRANSACTION_ID_PREFIX,
    Base,
    new_id,
    utcnow,
)
from app.models.enums import TransactionStatus, TransactionType, pg_enum

if TYPE_CHECKING:
    from app.models.assessment import Assessment
    from app.models.entity import Device, Entity
    from app.models.simulation import SimulationRun

#: Prefixes the simulator may set on a transaction's idempotency key. Any
#: non-empty string is allowed; the unique index is what guarantees dedup.
IDEMPOTENCY_KEY_LENGTH = 128


class Transaction(Base):
    """One simulated money movement.

    Identifier and deduplication scheme:

    * ``id`` is the natural key supplied by the simulator (``txn_...``), so
      replaying the same generated event is idempotent at the database level.
    * ``idempotency_key`` is an optional caller-supplied key for the scoring
      endpoint. It is unique when present, so a retried HTTP request cannot
      create a second row.
    * Both are backed by unique constraints; see
      :meth:`app.repositories.transactions.TransactionRepository.upsert`.

    Causality contract: the feature engine reads this table **only** through
    :meth:`~app.repositories.transactions.TransactionRepository.events_before`,
    which enforces ``timestamp < as_of`` and deterministic tie-breaking.
    """

    __tablename__ = "transactions"

    id: Mapped[str] = mapped_column(
        String(ID_LENGTH),
        primary_key=True,
        default=lambda: new_id(TRANSACTION_ID_PREFIX),
    )
    sender_id: Mapped[str] = mapped_column(
        ForeignKey("entities.entity_id", ondelete="RESTRICT"),
        nullable=False,
    )
    receiver_id: Mapped[str] = mapped_column(
        ForeignKey("entities.entity_id", ondelete="RESTRICT"),
        nullable=False,
    )
    #: Integer poisha. Never a float, never a string. Enforced non-negative.
    amount_poisha: Mapped[int] = mapped_column(BigInteger, nullable=False)
    #: Column is literally named ``type``; the attribute avoids shadowing
    #: nothing important but is mapped explicitly for clarity.
    type: Mapped[TransactionType] = mapped_column(
        "type",
        pg_enum(TransactionType, name="transaction_type"),
        nullable=False,
    )
    timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
    )
    device_id: Mapped[str | None] = mapped_column(
        ForeignKey("devices.device_id", ondelete="SET NULL"),
        nullable=True,
    )
    #: Synthetic location label (region/cell name), never a real coordinate.
    location: Mapped[str | None] = mapped_column(String(128), nullable=True)
    #: Simulated ledger resolution. Outcome data — never a scoring input.
    status: Mapped[TransactionStatus] = mapped_column(
        pg_enum(TransactionStatus, name="transaction_status"),
        nullable=False,
        default=TransactionStatus.COMPLETED,
    )
    #: Which simulation run produced this row. Null for seeded reference data.
    scenario_run_id: Mapped[str | None] = mapped_column(
        ForeignKey("simulation_runs.id", ondelete="CASCADE"),
        nullable=True,
    )
    #: Optional short untrusted description. Treated as data, never as
    #: instructions and never as an oracle available before scoring.
    description: Mapped[str | None] = mapped_column(Text, nullable=True)
    #: Unique when present. Multiple NULLs are permitted by PostgreSQL.
    idempotency_key: Mapped[str | None] = mapped_column(
        String(IDEMPOTENCY_KEY_LENGTH),
        nullable=True,
        unique=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=utcnow,
        server_default=func.now(),
    )

    sender: Mapped[Entity] = relationship(
        foreign_keys=[sender_id],
        back_populates="sent_transactions",
        lazy="raise",
    )
    receiver: Mapped[Entity] = relationship(
        foreign_keys=[receiver_id],
        back_populates="received_transactions",
        lazy="raise",
    )
    device: Mapped[Device | None] = relationship(lazy="raise")
    scenario_run: Mapped[SimulationRun | None] = relationship(
        back_populates="transactions",
        lazy="raise",
    )
    assessment: Mapped[Assessment | None] = relationship(
        back_populates="transaction",
        cascade="all, delete-orphan",
        uselist=False,
        lazy="raise",
    )

    __table_args__ = (
        # --- Mandatory access paths -------------------------------------
        # Transaction timestamp (global time scans / dashboard windows).
        Index("ix_transactions_timestamp", "timestamp"),
        # Sender/time and receiver/time, the causal-feature access paths.
        Index("ix_transactions_sender_timestamp", "sender_id", "timestamp"),
        Index("ix_transactions_receiver_timestamp", "receiver_id", "timestamp"),
        # --- Supporting paths -------------------------------------------
        Index("ix_transactions_type_timestamp", "type", "timestamp"),
        Index("ix_transactions_status_timestamp", "status", "timestamp"),
        Index(
            "ix_transactions_scenario_run_timestamp",
            "scenario_run_id",
            "timestamp",
        ),
        # --- Invariants --------------------------------------------------
        CheckConstraint("amount_poisha >= 0", name="amount_non_negative"),
        CheckConstraint("sender_id <> receiver_id", name="sender_not_receiver"),
    )

    def __repr__(self) -> str:  # pragma: no cover - debugging aid
        return (
            f"<Transaction {self.id} {self.sender_id}->{self.receiver_id} "
            f"{self.amount_poisha}poisha @{self.timestamp.isoformat()}>"
        )
